const MOOD_DATA_DB = {
    "sad": {
        "emoji": "\ud83e\udd7a",
        "messages": [
            "I'm sending you the biggest hug right now! \ud83d\udc96",
            "Take a deep breath baby, I love you more than anything \u2764\ufe0f",
            "Everything will be okay. I'm right by your side! \ud83d\udc9e\u2728",
            "Don't let anyone ruin your day! You mean everything to me \ud83e\udec2",
            "I wish I could kiss away your sadness! \ud83d\udc96",
            "You are so strong and amazing. Please cheer up! \ud83e\udec2",
            "It breaks my heart to see you sad. I am always here for you \ud83e\udec2",
            "Take a deep breath baby, I love you more than anything \ud83e\udec2",
            "Whenever you are sad, remember how much I adore you \ud83e\udd7a\ud83d\udc95",
            "Aww baby, please don't be sad. I love you! \ud83e\udd7a\ud83d\udc95",
            "I'm sending you the biggest hug right now! \ud83e\udd7a\ud83d\udc95",
            "Everything will be okay. I'm right by your side! \ud83e\udd7a\ud83d\udc95",
            "You are so strong and amazing. Please cheer up! \ud83d\udc9e\u2728",
            "I wish I could kiss away your sadness! \u2764\ufe0f",
            "I wish I could kiss away your sadness! \ud83e\udd7a\ud83d\udc95",
            "It breaks my heart to see you sad. I am always here for you \ud83d\udc96",
            "Whenever you are sad, remember how much I adore you \ud83d\udc96",
            "Aww baby, please don't be sad. I love you! \ud83d\udc9e\u2728",
            "You are so strong and amazing. Please cheer up! \ud83e\udd7a\ud83d\udc95",
            "It breaks my heart to see you sad. I am always here for you \u2764\ufe0f",
            "Take a deep breath baby, I love you more than anything \ud83d\udc9e\u2728",
            "Aww baby, please don't be sad. I love you! \ud83e\udec2",
            "Smile darling, you are the most beautiful person in the world! \ud83d\udc9e\u2728",
            "It breaks my heart to see you sad. I am always here for you \ud83d\udc9e\u2728",
            "Smile darling, you are the most beautiful person in the world! \ud83e\udec2",
            "Don't let anyone ruin your day! You mean everything to me \ud83e\udd7a\ud83d\udc95",
            "I wish I could kiss away your sadness! \ud83e\udec2",
            "Whenever you are sad, remember how much I adore you \ud83e\udec2",
            "Smile darling, you are the most beautiful person in the world! \ud83e\udd7a\ud83d\udc95",
            "Smile darling, you are the most beautiful person in the world! \u2764\ufe0f",
            "It breaks my heart to see you sad. I am always here for you \ud83e\udd7a\ud83d\udc95",
            "You are so strong and amazing. Please cheer up! \u2764\ufe0f",
            "Smile darling, you are the most beautiful person in the world! \ud83d\udc96",
            "Whenever you are sad, remember how much I adore you \ud83d\udc9e\u2728",
            "I'm sending you the biggest hug right now! \ud83e\udec2",
            "I'm sending you the biggest hug right now! \u2764\ufe0f",
            "You are so strong and amazing. Please cheer up! \ud83d\udc96",
            "I'm sending you the biggest hug right now! \ud83d\udc9e\u2728",
            "I wish I could kiss away your sadness! \ud83d\udc9e\u2728",
            "Don't let anyone ruin your day! You mean everything to me \ud83d\udc9e\u2728",
            "Don't let anyone ruin your day! You mean everything to me \ud83d\udc96",
            "Aww baby, please don't be sad. I love you! \u2764\ufe0f",
            "Take a deep breath baby, I love you more than anything \ud83e\udd7a\ud83d\udc95",
            "Everything will be okay. I'm right by your side! \ud83d\udc96",
            "Whenever you are sad, remember how much I adore you \u2764\ufe0f",
            "Take a deep breath baby, I love you more than anything \ud83d\udc96",
            "Everything will be okay. I'm right by your side! \ud83e\udec2",
            "Aww baby, please don't be sad. I love you! \ud83d\udc96",
            "Don't let anyone ruin your day! You mean everything to me \u2764\ufe0f",
            "Everything will be okay. I'm right by your side! \u2764\ufe0f"
        ]
    },
    "angry": {
        "emoji": "\ud83d\ude24",
        "messages": [
            "Who do I need to fight? Nobody messes with my darling! \ud83d\ude21\ud83d\udc95",
            "Close your eyes and think of how much I love you. \ud83e\udd4a\ud83d\udc96",
            "Don't let them get to you, you are perfect! \ud83d\ude24\u2764\ufe0f",
            "You look so cute when you're mad, but please calm down! \ud83d\udd25",
            "Take a deep breath baby! Whoever upset you is wrong. \ud83d\ude21\ud83d\udc95",
            "Drink some water sweetheart, don't waste energy being mad. \ud83e\udec2\u2728",
            "You look so cute when you're mad, but please calm down! \ud83e\udd4a\ud83d\udc96",
            "You're too cute to be angry! I love you so much. \ud83d\udd25",
            "Relax my love. I'm here to give you massages and kisses. \ud83e\udec2\u2728",
            "You're too cute to be angry! I love you so much. \ud83d\ude24\u2764\ufe0f",
            "You're too cute to be angry! I love you so much. \ud83d\ude21\ud83d\udc95",
            "Relax my love. I'm here to give you massages and kisses. \ud83d\udd25",
            "Drink some water sweetheart, don't waste energy being mad. \ud83d\ude21\ud83d\udc95",
            "Relax my love. I'm here to give you massages and kisses. \ud83d\ude24\u2764\ufe0f",
            "Who do I need to fight? Nobody messes with my darling! \ud83d\udd25",
            "Who do I need to fight? Nobody messes with my darling! \ud83e\udd4a\ud83d\udc96",
            "Take a deep breath baby! Whoever upset you is wrong. \ud83d\ude24\u2764\ufe0f",
            "Let it all out baby, I'm listening to you complain! \ud83e\udd4a\ud83d\udc96",
            "Let it all out baby, I'm listening to you complain! \ud83d\ude21\ud83d\udc95",
            "Let it all out baby, I'm listening to you complain! \ud83e\udec2\u2728",
            "Who do I need to fight? Nobody messes with my darling! \ud83e\udec2\u2728",
            "Don't let them get to you, you are perfect! \ud83d\udd25",
            "I'll fight whoever made my darling angry! \ud83e\udd4a\ud83d\udc96",
            "Relax my love. I'm here to give you massages and kisses. \ud83d\ude21\ud83d\udc95",
            "I'll fight whoever made my darling angry! \ud83e\udec2\u2728",
            "You're too cute to be angry! I love you so much. \ud83e\udd4a\ud83d\udc96",
            "Drink some water sweetheart, don't waste energy being mad. \ud83d\udd25",
            "Take a deep breath baby! Whoever upset you is wrong. \ud83e\udec2\u2728",
            "Let it all out baby, I'm listening to you complain! \ud83d\ude24\u2764\ufe0f",
            "Don't let them get to you, you are perfect! \ud83e\udec2\u2728",
            "Don't let them get to you, you are perfect! \ud83e\udd4a\ud83d\udc96",
            "You look so cute when you're mad, but please calm down! \ud83d\ude24\u2764\ufe0f",
            "Don't let them get to you, you are perfect! \ud83d\ude21\ud83d\udc95",
            "Close your eyes and think of how much I love you. \ud83d\ude24\u2764\ufe0f",
            "Relax my love. I'm here to give you massages and kisses. \ud83e\udd4a\ud83d\udc96",
            "Drink some water sweetheart, don't waste energy being mad. \ud83d\ude24\u2764\ufe0f",
            "You look so cute when you're mad, but please calm down! \ud83d\ude21\ud83d\udc95",
            "You look so cute when you're mad, but please calm down! \ud83e\udec2\u2728",
            "Take a deep breath baby! Whoever upset you is wrong. \ud83e\udd4a\ud83d\udc96",
            "I'll fight whoever made my darling angry! \ud83d\udd25",
            "Close your eyes and think of how much I love you. \ud83d\ude21\ud83d\udc95",
            "I'll fight whoever made my darling angry! \ud83d\ude24\u2764\ufe0f",
            "Drink some water sweetheart, don't waste energy being mad. \ud83e\udd4a\ud83d\udc96",
            "Take a deep breath baby! Whoever upset you is wrong. \ud83d\udd25",
            "You're too cute to be angry! I love you so much. \ud83e\udec2\u2728",
            "Who do I need to fight? Nobody messes with my darling! \ud83d\ude24\u2764\ufe0f",
            "Let it all out baby, I'm listening to you complain! \ud83d\udd25",
            "Close your eyes and think of how much I love you. \ud83e\udec2\u2728",
            "I'll fight whoever made my darling angry! \ud83d\ude21\ud83d\udc95",
            "Close your eyes and think of how much I love you. \ud83d\udd25"
        ]
    },
    "sleepy": {
        "emoji": "\ud83d\ude34",
        "messages": [
            "You must be exhausted from being perfect all day. Rest up! \u2728\ud83d\udc96",
            "You must be exhausted from being perfect all day. Rest up! \ud83d\udca4",
            "I'll be dreaming of you! Sleep well my love. \ud83d\udca4",
            "Time for bed cutie. I love you to the moon and back. \ud83d\udecc\ud83d\udc95",
            "Can't wait to talk to you tomorrow. Have the best sleep! \ud83d\udecc\ud83d\udc95",
            "Sweet dreams beautiful! Go get some rest. \ud83d\udecc\ud83d\udc95",
            "Wrap yourself in a blanket and imagine it's me hugging you. \ud83d\udca4",
            "Wrap yourself in a blanket and imagine it's me hugging you. \ud83d\ude34\ud83c\udf19",
            "Sweet dreams beautiful! Go get some rest. \u2728\ud83d\udc96",
            "Time for bed cutie. I love you to the moon and back. \ud83e\uddf8\u2764\ufe0f",
            "You must be exhausted from being perfect all day. Rest up! \ud83e\uddf8\u2764\ufe0f",
            "Time for bed cutie. I love you to the moon and back. \ud83d\udca4",
            "Goodnight my love. I'll protect your sweet dreams. \ud83e\uddf8\u2764\ufe0f",
            "Goodnight my love. I'll protect your sweet dreams. \ud83d\ude34\ud83c\udf19",
            "Go lock your phone and sleep! You need it. \u2728\ud83d\udc96",
            "You must be exhausted from being perfect all day. Rest up! \ud83d\ude34\ud83c\udf19",
            "Sleep well sweetheart, I am sending you a billion goodnight kisses. \ud83e\uddf8\u2764\ufe0f",
            "Go lock your phone and sleep! You need it. \ud83d\udca4",
            "Wrap yourself in a blanket and imagine it's me hugging you. \u2728\ud83d\udc96",
            "Sleep well sweetheart, I am sending you a billion goodnight kisses. \u2728\ud83d\udc96",
            "Sleep well sweetheart, I am sending you a billion goodnight kisses. \ud83d\ude34\ud83c\udf19",
            "Go lock your phone and sleep! You need it. \ud83d\ude34\ud83c\udf19",
            "Sweet dreams beautiful! Go get some rest. \ud83d\udca4",
            "Wrap yourself in a blanket and imagine it's me hugging you. \ud83e\uddf8\u2764\ufe0f",
            "Sleep well sweetheart, I am sending you a billion goodnight kisses. \ud83d\udecc\ud83d\udc95",
            "Time for bed cutie. I love you to the moon and back. \ud83d\ude34\ud83c\udf19",
            "Close those beautiful eyes cutie. Sleep tight! \ud83d\udecc\ud83d\udc95",
            "Goodnight my love. I'll protect your sweet dreams. \ud83d\udca4",
            "Close those beautiful eyes cutie. Sleep tight! \u2728\ud83d\udc96",
            "I'll be dreaming of you! Sleep well my love. \ud83e\uddf8\u2764\ufe0f",
            "Wrap yourself in a blanket and imagine it's me hugging you. \ud83d\udecc\ud83d\udc95",
            "Sweet dreams beautiful! Go get some rest. \ud83e\uddf8\u2764\ufe0f",
            "Sleep well sweetheart, I am sending you a billion goodnight kisses. \ud83d\udca4",
            "I'll be dreaming of you! Sleep well my love. \u2728\ud83d\udc96",
            "Sweet dreams beautiful! Go get some rest. \ud83d\ude34\ud83c\udf19",
            "Can't wait to talk to you tomorrow. Have the best sleep! \ud83d\ude34\ud83c\udf19",
            "Close those beautiful eyes cutie. Sleep tight! \ud83d\udca4",
            "Can't wait to talk to you tomorrow. Have the best sleep! \ud83d\udca4",
            "Go lock your phone and sleep! You need it. \ud83d\udecc\ud83d\udc95",
            "I'll be dreaming of you! Sleep well my love. \ud83d\ude34\ud83c\udf19",
            "Close those beautiful eyes cutie. Sleep tight! \ud83d\ude34\ud83c\udf19",
            "Can't wait to talk to you tomorrow. Have the best sleep! \u2728\ud83d\udc96",
            "Goodnight my love. I'll protect your sweet dreams. \ud83d\udecc\ud83d\udc95",
            "Close those beautiful eyes cutie. Sleep tight! \ud83e\uddf8\u2764\ufe0f",
            "You must be exhausted from being perfect all day. Rest up! \ud83d\udecc\ud83d\udc95",
            "Go lock your phone and sleep! You need it. \ud83e\uddf8\u2764\ufe0f",
            "I'll be dreaming of you! Sleep well my love. \ud83d\udecc\ud83d\udc95",
            "Time for bed cutie. I love you to the moon and back. \u2728\ud83d\udc96",
            "Can't wait to talk to you tomorrow. Have the best sleep! \ud83e\uddf8\u2764\ufe0f",
            "Goodnight my love. I'll protect your sweet dreams. \u2728\ud83d\udc96"
        ]
    },
    "happy": {
        "emoji": "\ud83e\udd70",
        "messages": [
            "Your joy completely brightens up my day. \ud83c\udf38",
            "Seeing you happy makes me the happiest person alive! \ud83d\udc95\ud83c\udf89",
            "That's my girl! Always smiling and shining. \ud83d\udc95\ud83c\udf89",
            "I love seeing my darling in a good mood! \ud83d\udc96\u2728",
            "You're glowing darling! Keep that amazing energy. \ud83e\udd70\u2600\ufe0f",
            "Your joy completely brightens up my day. \u2764\ufe0f\ud83e\udd42",
            "I fall in love with you all over again when you're happy. \ud83d\udc96\u2728",
            "I love seeing my darling in a good mood! \u2764\ufe0f\ud83e\udd42",
            "Your joy completely brightens up my day. \ud83d\udc95\ud83c\udf89",
            "I fall in love with you all over again when you're happy. \ud83e\udd70\u2600\ufe0f",
            "You deserve all the happiness in the world! \ud83d\udc96\u2728",
            "I love seeing my darling in a good mood! \ud83d\udc95\ud83c\udf89",
            "Keep smiling my love! Your smile is my favorite thing. \ud83c\udf38",
            "Celebrate this good mood! I love you endlessly. \ud83d\udc95\ud83c\udf89",
            "You deserve all the happiness in the world! \ud83c\udf38",
            "I fall in love with you all over again when you're happy. \ud83d\udc95\ud83c\udf89",
            "Keep smiling my love! Your smile is my favorite thing. \ud83d\udc95\ud83c\udf89",
            "I love seeing my darling in a good mood! \ud83e\udd70\u2600\ufe0f",
            "I hope whatever made you happy stays forever! \ud83c\udf38",
            "Celebrate this good mood! I love you endlessly. \ud83d\udc96\u2728",
            "Seeing you happy makes me the happiest person alive! \ud83d\udc96\u2728",
            "You deserve all the happiness in the world! \ud83e\udd70\u2600\ufe0f",
            "That's my girl! Always smiling and shining. \ud83e\udd70\u2600\ufe0f",
            "That's my girl! Always smiling and shining. \ud83d\udc96\u2728",
            "Your joy completely brightens up my day. \ud83e\udd70\u2600\ufe0f",
            "Seeing you happy makes me the happiest person alive! \u2764\ufe0f\ud83e\udd42",
            "I fall in love with you all over again when you're happy. \u2764\ufe0f\ud83e\udd42",
            "Keep smiling my love! Your smile is my favorite thing. \ud83e\udd70\u2600\ufe0f",
            "You're glowing darling! Keep that amazing energy. \ud83d\udc95\ud83c\udf89",
            "Seeing you happy makes me the happiest person alive! \ud83c\udf38",
            "You're glowing darling! Keep that amazing energy. \ud83d\udc96\u2728",
            "I hope whatever made you happy stays forever! \u2764\ufe0f\ud83e\udd42",
            "You deserve all the happiness in the world! \u2764\ufe0f\ud83e\udd42",
            "Keep smiling my love! Your smile is my favorite thing. \u2764\ufe0f\ud83e\udd42",
            "I hope whatever made you happy stays forever! \ud83d\udc95\ud83c\udf89",
            "Your joy completely brightens up my day. \ud83d\udc96\u2728",
            "I hope whatever made you happy stays forever! \ud83d\udc96\u2728",
            "I fall in love with you all over again when you're happy. \ud83c\udf38",
            "Celebrate this good mood! I love you endlessly. \ud83e\udd70\u2600\ufe0f",
            "You deserve all the happiness in the world! \ud83d\udc95\ud83c\udf89",
            "Celebrate this good mood! I love you endlessly. \u2764\ufe0f\ud83e\udd42",
            "You're glowing darling! Keep that amazing energy. \u2764\ufe0f\ud83e\udd42",
            "Seeing you happy makes me the happiest person alive! \ud83e\udd70\u2600\ufe0f",
            "That's my girl! Always smiling and shining. \ud83c\udf38",
            "I hope whatever made you happy stays forever! \ud83e\udd70\u2600\ufe0f",
            "I love seeing my darling in a good mood! \ud83c\udf38",
            "Celebrate this good mood! I love you endlessly. \ud83c\udf38",
            "You're glowing darling! Keep that amazing energy. \ud83c\udf38",
            "That's my girl! Always smiling and shining. \u2764\ufe0f\ud83e\udd42",
            "Keep smiling my love! Your smile is my favorite thing. \ud83d\udc96\u2728"
        ]
    },
    "stressed": {
        "emoji": "\ud83d\udc86\u200d\u2640\ufe0f",
        "messages": [
            "Close your eyes for 5 minutes sweetheart. Relax your shoulders. \ud83d\udca7\ud83d\udc95",
            "Close your eyes for 5 minutes sweetheart. Relax your shoulders. \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "Don't panic my love! You are stronger than any problem. \ud83d\udcaa\ud83d\udc96",
            "I wish I could take your stress away. Sending you a back rub! \ud83d\udcaa\ud83d\udc96",
            "You're doing amazing! Take a break, drink some water. \ud83e\udec2\u2728",
            "Don't panic my love! You are stronger than any problem. \ud83d\udcda\u2764\ufe0f",
            "Everything will work out perfectly. Trust yourself! \ud83e\udec2\u2728",
            "Close your eyes for 5 minutes sweetheart. Relax your shoulders. \ud83d\udcda\u2764\ufe0f",
            "It will all be over soon. You are incredibly smart and capable! \ud83d\udcaa\ud83d\udc96",
            "Everything will work out perfectly. Trust yourself! \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "You're doing amazing! Take a break, drink some water. \ud83d\udcaa\ud83d\udc96",
            "Don't panic my love! You are stronger than any problem. \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "It will all be over soon. You are incredibly smart and capable! \ud83d\udca7\ud83d\udc95",
            "Whenever you feel stressed, just remember I'm rooting for you. \ud83d\udcaa\ud83d\udc96",
            "You're doing amazing! Take a break, drink some water. \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "Close your eyes for 5 minutes sweetheart. Relax your shoulders. \ud83d\udcaa\ud83d\udc96",
            "Don't overwork yourself my love. I believe in you! \ud83d\udcda\u2764\ufe0f",
            "It will all be over soon. You are incredibly smart and capable! \ud83e\udec2\u2728",
            "Everything will work out perfectly. Trust yourself! \ud83d\udcaa\ud83d\udc96",
            "Take it one step at a time. You've got this! \ud83e\udec2\u2728",
            "Take it one step at a time. You've got this! \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "Whenever you feel stressed, just remember I'm rooting for you. \ud83d\udca7\ud83d\udc95",
            "Don't panic my love! You are stronger than any problem. \ud83e\udec2\u2728",
            "You work so hard, but remember your health comes first. \ud83d\udca7\ud83d\udc95",
            "You're doing amazing! Take a break, drink some water. \ud83d\udcda\u2764\ufe0f",
            "Everything will work out perfectly. Trust yourself! \ud83d\udcda\u2764\ufe0f",
            "I wish I could take your stress away. Sending you a back rub! \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "You're doing amazing! Take a break, drink some water. \ud83d\udca7\ud83d\udc95",
            "You work so hard, but remember your health comes first. \ud83e\udec2\u2728",
            "Take it one step at a time. You've got this! \ud83d\udcaa\ud83d\udc96",
            "Don't overwork yourself my love. I believe in you! \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "Don't overwork yourself my love. I believe in you! \ud83d\udcaa\ud83d\udc96",
            "It will all be over soon. You are incredibly smart and capable! \ud83d\udcda\u2764\ufe0f",
            "I wish I could take your stress away. Sending you a back rub! \ud83d\udcda\u2764\ufe0f",
            "It will all be over soon. You are incredibly smart and capable! \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "Don't overwork yourself my love. I believe in you! \ud83e\udec2\u2728",
            "Whenever you feel stressed, just remember I'm rooting for you. \ud83e\udec2\u2728",
            "You work so hard, but remember your health comes first. \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "Whenever you feel stressed, just remember I'm rooting for you. \ud83d\udcda\u2764\ufe0f",
            "Close your eyes for 5 minutes sweetheart. Relax your shoulders. \ud83e\udec2\u2728",
            "You work so hard, but remember your health comes first. \ud83d\udcda\u2764\ufe0f",
            "Don't panic my love! You are stronger than any problem. \ud83d\udca7\ud83d\udc95",
            "Whenever you feel stressed, just remember I'm rooting for you. \ud83d\udc86\u200d\u2640\ufe0f\ud83c\udf38",
            "Don't overwork yourself my love. I believe in you! \ud83d\udca7\ud83d\udc95",
            "I wish I could take your stress away. Sending you a back rub! \ud83d\udca7\ud83d\udc95",
            "I wish I could take your stress away. Sending you a back rub! \ud83e\udec2\u2728",
            "Take it one step at a time. You've got this! \ud83d\udcda\u2764\ufe0f",
            "Everything will work out perfectly. Trust yourself! \ud83d\udca7\ud83d\udc95",
            "You work so hard, but remember your health comes first. \ud83d\udcaa\ud83d\udc96",
            "Take it one step at a time. You've got this! \ud83d\udca7\ud83d\udc95"
        ]
    },
    "hungry": {
        "emoji": "\ud83e\udd24",
        "messages": [
            "Don't starve my my love! Order something delicious right now. \ud83c\udf54\u2764\ufe0f",
            "You deserve a massive feast. Treat yourself! \ud83e\udd42\u2728",
            "What are you craving? Go get it beautiful! \ud83c\udf69\ud83d\udc96",
            "Stop what you're doing and go eat! I love you. \ud83c\udf54\u2764\ufe0f",
            "Stop what you're doing and go eat! I love you. \ud83c\udf55\ud83d\udc95",
            "Grab a little snack at least! You need your energy. \ud83e\udd42\u2728",
            "Stop what you're doing and go eat! I love you. \ud83e\udd24\ud83c\udf5f",
            "You deserve a massive feast. Treat yourself! \ud83c\udf54\u2764\ufe0f",
            "You deserve a massive feast. Treat yourself! \ud83c\udf55\ud83d\udc95",
            "I'm virtually sending you your favorite meal. Now go eat in real life! \ud83c\udf69\ud83d\udc96",
            "You deserve a massive feast. Treat yourself! \ud83e\udd24\ud83c\udf5f",
            "Don't starve my my love! Order something delicious right now. \ud83e\udd24\ud83c\udf5f",
            "I'm virtually sending you your favorite meal. Now go eat in real life! \ud83c\udf55\ud83d\udc95",
            "I'm virtually sending you your favorite meal. Now go eat in real life! \ud83e\udd42\u2728",
            "Grab a little snack at least! You need your energy. \ud83c\udf55\ud83d\udc95",
            "Grab a little snack at least! You need your energy. \ud83c\udf54\u2764\ufe0f",
            "My baby needs fuel to stay cute! Go grab food. \ud83e\udd24\ud83c\udf5f",
            "I wish I could cook for you! Go eat cutie. \ud83e\udd24\ud83c\udf5f",
            "A hungry cutie is an angry cutie. Please eat! \ud83e\udd42\u2728",
            "I wish I could cook for you! Go eat cutie. \ud83c\udf54\u2764\ufe0f",
            "A hungry cutie is an angry cutie. Please eat! \ud83e\udd24\ud83c\udf5f",
            "My baby needs fuel to stay cute! Go grab food. \ud83c\udf69\ud83d\udc96",
            "What are you craving? Go get it beautiful! \ud83c\udf55\ud83d\udc95",
            "My baby needs fuel to stay cute! Go grab food. \ud83e\udd42\u2728",
            "A hungry cutie is an angry cutie. Please eat! \ud83c\udf55\ud83d\udc95",
            "Don't starve my my love! Order something delicious right now. \ud83e\udd42\u2728",
            "Don't starve my my love! Order something delicious right now. \ud83c\udf55\ud83d\udc95",
            "My baby needs fuel to stay cute! Go grab food. \ud83c\udf55\ud83d\udc95",
            "What are you craving? Go get it beautiful! \ud83e\udd24\ud83c\udf5f",
            "I'm virtually sending you your favorite meal. Now go eat in real life! \ud83c\udf54\u2764\ufe0f",
            "Grab a little snack at least! You need your energy. \ud83e\udd24\ud83c\udf5f",
            "Time for a snack baby! Go get something yummy. \ud83c\udf69\ud83d\udc96",
            "A hungry cutie is an angry cutie. Please eat! \ud83c\udf54\u2764\ufe0f",
            "Time for a snack baby! Go get something yummy. \ud83c\udf54\u2764\ufe0f",
            "What are you craving? Go get it beautiful! \ud83c\udf54\u2764\ufe0f",
            "My baby needs fuel to stay cute! Go grab food. \ud83c\udf54\u2764\ufe0f",
            "I wish I could cook for you! Go eat cutie. \ud83c\udf69\ud83d\udc96",
            "I wish I could cook for you! Go eat cutie. \ud83e\udd42\u2728",
            "Time for a snack baby! Go get something yummy. \ud83e\udd42\u2728",
            "You deserve a massive feast. Treat yourself! \ud83c\udf69\ud83d\udc96",
            "I wish I could cook for you! Go eat cutie. \ud83c\udf55\ud83d\udc95",
            "Grab a little snack at least! You need your energy. \ud83c\udf69\ud83d\udc96",
            "Stop what you're doing and go eat! I love you. \ud83c\udf69\ud83d\udc96",
            "What are you craving? Go get it beautiful! \ud83e\udd42\u2728",
            "I'm virtually sending you your favorite meal. Now go eat in real life! \ud83e\udd24\ud83c\udf5f",
            "Don't starve my my love! Order something delicious right now. \ud83c\udf69\ud83d\udc96",
            "A hungry cutie is an angry cutie. Please eat! \ud83c\udf69\ud83d\udc96",
            "Time for a snack baby! Go get something yummy. \ud83c\udf55\ud83d\udc95",
            "Stop what you're doing and go eat! I love you. \ud83e\udd42\u2728",
            "Time for a snack baby! Go get something yummy. \ud83e\udd24\ud83c\udf5f"
        ]
    }
};
